/*
 * This file automatically generated by shim.py.

 * EDIT AT YOUR PERIL.
 */
/*
 * Contains a union of structs, each one containing 
 * a copy of the parameters used by the corresponding
 * MPI function call, as well as a handful of book-
 * keeping variables.  Using a union keeps the 
 * instatiated size down, as well as eliminating
 * namespace clashes caused by different structs using
 * the same variable names.
 */
#include <mpi.h>
#include "shim_structs.h"
union shim_parameters {
#include "shim_union.h"
};
